all: main

main: main.o main complex.o
	g++ main.o complex.o -o main

main: main.cpp
        g++ -c main.cpp -o main.o

complex.o: complex.cpp
        g++ -c complex.cpp -o complex.o

clean:
        rm *.o main
